(() => {
  'use strict';
  const A = window.Mambo, P = window.MamboPerformance, $ = s => document.querySelector(s);
  const esc = v => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon = n => `<svg aria-hidden="true"><use href="#i-${n}"/></svg>`;
  const screens = [['home','Home','home'],['explore','Explore','search'],['community','Community','chat'],['collections','Collections','bookmark'],['activity','Activity','fire']];
  const people = [{name:'Mira',handle:'mira.frames',letter:'M',bio:'Slow cinema. Big feelings. A very long watchlist.'},{name:'Aryan',handle:'aryan.aftercredits',letter:'A',bio:'Here for the plot twists and the post-credits conversation.'},{name:'Janwi',handle:'janwi.watches',letter:'J',bio:'One more episode is a perfectly reasonable plan.'}];
  const lists = [{name:'Weekend Binge',copy:'Cancel your plans. Keep the popcorn.',ids:['s95396','s70523','s1396','s136315']},{name:'Sci-Fi Deep Dives',copy:'A little further from the ordinary.',ids:['m157336','m693134','m27205','m335984','m545611']},{name:'Comfort Rewatches',copy:'The stories that feel like coming home.',ids:['m120467','m129','a32281','m313369']}];
  const social = A.state.social;
  for (const k of ['likes','follows','comments']) if (!social[k] || typeof social[k] !== 'object' || Array.isArray(social[k])) social[k] = {};
  let current='home', search='', tag='All', tourTimer, hubVisible=false, direction=1;
  const titles = () => A.catalog[A.state.mode];
  const card = (t,i=0) => `<article class="hub-card"><button class="hub-art" data-title="${t.id}" aria-label="Explore ${esc(t.title)}"><img loading="lazy" decoding="async" src="${t.image}" alt="${esc(t.title)} poster">${i%4===0?'<span class="hub-friend"><i>M</i><i>J</i> Demo friends saved</span>':''}</button><button class="hub-save ${A.state.saves[t.id]?'saved':''}" data-save="${t.id}" aria-label="Save ${esc(t.title)}">${A.state.saves[t.id]?'✓':'+'}</button><strong>${esc(t.title)}</strong><small>${t.year}<b>★ ${t.score}</b></small></article>`;
  const shelf = (title,items,id) => `<section class="hub-shelf"><div class="hub-section-head"><h3>${title}</h3><div><button data-shelf="${id}" data-step="-1" aria-label="Scroll ${esc(title)} left">←</button><button data-shelf="${id}" data-step="1" aria-label="Scroll ${esc(title)} right">→</button></div></div><div class="hub-poster-row" id="${id}">${items.map(card).join('')}</div></section>`;
  const feed = () => people.map((p,i)=>{
    const t=titles()[i], key=A.state.mode+'-'+i;
    const quote=['That feeling when the credits roll and you just sit there. This is why I love stories.','Went in knowing nothing. Left with a new obsession. Someone please watch this so we can talk.','Adding this to my permanent personality. The rewatch is already planned.'][i];
    return `<article class="feed-card"><div class="feed-user"><button class="social-avatar avatar-${i}" data-person="${i}" aria-label="View ${p.name}'s demo profile">${p.letter}</button><div><button data-person="${i}">${p.name}</button><small>@${p.handle} · Sample review</small></div><button class="follow-button" data-follow="${i}" aria-pressed="${!!social.follows[i]}">${social.follows[i]?'Following':'Follow +'}</button></div><div class="feed-review"><button data-title="${t.id}" class="feed-poster"><img src="${t.image}" alt="${esc(t.title)}" loading="lazy" decoding="async"></button><div><button class="feed-title" data-title="${t.id}">${esc(t.title)}</button><p class="accent">${i===1?'★★★★½':'★★★★★'}</p><p>${quote}</p><span class="caps">${i===2?'COMFORT WATCH':'RECOMMENDED'}</span></div></div><div class="feed-actions"><button data-like="${key}" aria-pressed="${!!social.likes[key]}">${social.likes[key]?'♥':'♡'} ${24+i*13+(social.likes[key]?1:0)}</button><button data-comments="${i}">${icon('chat')} ${Array.isArray(social.comments[key])?social.comments[key].length:0} comments</button><button data-save="${t.id}" aria-label="Save ${esc(t.title)}">${A.state.saves[t.id]?'✓':'+'}</button></div></article>`;
  }).join('');
  function exploreResults() {
    const result=titles().filter(t=>(tag==='All'||t.tag===tag)&&`${t.title} ${t.meta} ${t.tag}`.toLowerCase().includes(search.toLowerCase()));
    $('#hubResults').innerHTML=result.map(card).join('') || '<div class="hub-empty">No stories found. Try another title, genre, or mood.</div>';
    $('#hubResultCount').textContent=result.length+' stories to fall into';
  }
  function render(animate=false) {
    $('#hubNav').innerHTML=screens.map(([id,label,symbol])=>`<button data-hub="${id}" aria-pressed="${current===id}" class="${current===id?'active':''}">${icon(symbol)}<span>${label}</span>${id==='community'?'<i>3</i>':''}</button>`).join('')+`<a href="#people">${icon('chat')}<span>Messages</span></a><a href="#profile">${icon('user')}<span>Profile</span></a>`;
    $('#hubModes').innerHTML=Object.keys(A.catalog).map(m=>`<button data-mode="${m}" aria-pressed="${m===A.state.mode}">${m}</button>`).join('');
    $('#hubScreenName').textContent=screens.find(x=>x[0]===current)[1]+' / '+A.state.mode;
    $('#performanceMode').value=P.preference;
    $('#hubStatus').textContent=P.lite?'Lite experience · No WebGL, no decorative motion · Data stays on this device':'Interactive preview · Sample community, not live activity · Swipe sideways or use the arrows to change screens';
    const t=titles()[0]; let html='';
    if(current==='home') {
      const watching=Object.keys(A.state.saves).map(A.byId).find(t=>t&&A.state.saves[t.id].status==='Watching') || A.catalog.series[0];
      html=`<div class="hub-welcome"><p class="caps">GOOD STORIES. BETTER COMPANY.</p><h3>Your kind of <span class="accent">universe.</span></h3><p>Pick up where you left off. Or fall into something new.</p></div><div class="hub-feature"><img class="hub-feature-backdrop" src="${t.image}" alt="" decoding="async"><div><p class="caps">TONIGHT'S MAIN CHARACTER</p><h4>${esc(t.title)}</h4><p>${esc(t.description)}</p><div class="hub-feature-actions"><button class="btn primary" data-title="${t.id}">Explore title ↗</button><button class="btn outline" data-action="swipe">Find my next watch</button></div></div><button class="hub-feature-poster" data-title="${t.id}"><img src="${t.image}" alt="${esc(t.title)} poster"></button></div><div class="hub-watch-next"><div class="social-avatar">▷</div><div><span class="caps">CONTINUE THE OBSESSION</span><strong>${esc(watching.title)}</strong><small>${A.state.saves[watching.id]?'Your tracked title':'Try the episode tracker'}</small></div><button class="btn outline" data-track-title="${watching.id}">Open tracker +1</button></div>${shelf('Made for your watchlist',titles().slice(1), 'hubShelfHome')}<div class="hub-people-strip"><div class="avatar-stack">${people.map((p,i)=>`<button data-person="${i}" class="social-avatar avatar-${i}" aria-label="View ${p.name}">${p.letter}</button>`).join('')}</div><p>The best part is talking about it.<small>Step inside the sample community.</small></p><button data-hub="community">Meet your people ↗</button></div>`;
    } else if(current==='explore') {
      html=`<div class="hub-welcome"><p class="caps">DISCOVER SOMETHING WORTH YOUR TIME</p><h3>Follow the <span class="accent">feeling.</span></h3></div><label class="hub-search">${icon('search')}<input id="hubSearch" type="search" value="${esc(search)}" placeholder="Search movies, series, anime..." aria-label="Search app catalog"></label><div class="hub-tags">${['All',...new Set(titles().map(t=>t.tag))].map(x=>`<button class="filter-chip ${tag===x?'active':''}" data-hub-tag="${esc(x)}" aria-pressed="${tag===x}">${x}</button>`).join('')}</div><p class="hub-result-count" id="hubResultCount" role="status"></p><div id="hubResults" class="hub-grid"></div>`;
    } else if(current==='community') {
      html=`<div class="hub-welcome"><p class="caps">FOR THE PEOPLE. FOR THE PLOT.</p><h3>Your post-credits <span class="accent">club.</span></h3><p>Sample profiles and reviews. Likes, follows, and comments are saved locally.</p></div><div class="hub-community"><div id="hubFeed">${feed()}</div><aside class="hub-community-aside"><p class="caps accent">PEOPLE WITH GOOD TASTE</p>${people.map((p,i)=>`<button class="community-person" data-person="${i}"><span class="social-avatar avatar-${i}">${p.letter}</span><span><strong>${p.name}</strong><small>@${p.handle}</small></span>↗</button>`).join('')}<div class="community-prompt"><p class="caps">THE BIG QUESTION</p><h4>Which film would you erase from your memory just to watch again?</h4><button data-comments="0">Join the conversation ↗</button></div><button class="btn outline" data-action="share">Write your own review ↗</button></aside></div>`;
    } else if(current==='collections') {
      html=`<div class="hub-welcome"><p class="caps">A LITTLE ORGANIZED CHAOS</p><h3>A collection for <span class="accent">every mood.</span></h3><p>Editorial starter lists. Make them yours with one tap.</p></div><div class="hub-list-grid">${lists.map((l,i)=>`<article class="hub-list"><button class="list-covers" data-list="${i}" aria-label="Open ${l.name}">${l.ids.slice(0,3).map(id=>`<img src="${A.byId(id).image}" alt="${esc(A.byId(id).title)}" loading="lazy">`).join('')}</button><h4>${l.name}</h4><p>${l.copy}</p><small>${l.ids.length} titles · Mambo edit</small><button data-list="${i}">Explore collection ↗</button></article>`).join('')}</div><div class="hub-people-strip"><p>Your own universe is waiting.<small>Watched, Watchlist, Dropped, Favorites, and your sub-groups.</small></p><button data-action="library">Open your library ↗</button></div>`;
    } else {
      const saved=Object.entries(A.state.saves).filter(([id])=>A.byId(id));
      html=`<div class="hub-welcome"><p class="caps">A LIFE IN STORIES</p><h3>Your watch <span class="accent">journal.</span></h3><p>This is your real local activity, not a sample feed.</p></div><div class="hub-stats"><div><b>${saved.length}</b><span>Tracked titles</span></div><div><b>${Object.values(A.state.favorites).filter(Boolean).length}</b><span>Favorites</span></div><div><b>${Object.values(A.state.ratings).filter(n=>n>0).length}</b><span>Rated</span></div></div>${saved.length?saved.map(([id,s])=>{const t=A.byId(id);return `<button class="hub-activity" data-title="${id}"><img src="${t.image}" alt="${esc(t.title)}" loading="lazy"><span><strong>${esc(t.title)}</strong><small>${esc(s.status)} · ${esc(s.folder)}</small></span><b class="accent">${A.state.ratings[id]?'★ '+A.state.ratings[id]:'↗'}</b></button>`;}).join(''):'<div class="hub-empty"><h4>Every great watch starts somewhere.</h4><p>Save a title or track an episode to start your journal.</p><button class="btn primary" data-hub="explore">Find your first obsession ↗</button></div>'}${shelf('Your next diary entry?',titles().slice(0,6),'hubShelfActivity')}`;
    }
    $('#hubScreen').innerHTML=html;
    if(current==='explore') { exploreResults(); $('#hubSearch').oninput=e=>{search=e.target.value;exploreResults();}; }
    $('#hubScreen').getAnimations().forEach(animation=>animation.cancel());
    if(animate&&!A.reduced&&!P.lite) $('#hubScreen').animate([{opacity:.15,transform:`translate3d(${direction*32}px,0,-60px) rotateY(${direction*3}deg) scale(.98)`},{opacity:1,transform:'none'}],{duration:380,easing:'cubic-bezier(.22,1,.36,1)'});
  }
  function stopTour() {clearInterval(tourTimer);tourTimer=null;$('#hubTour').textContent='Screen tour ▷';$('#hubTour').setAttribute('aria-pressed','false');}
  function navigate(id,fromTour=false) { if(!screens.some(s=>s[0]===id))return; if(!fromTour)stopTour(); const restore=$('#hubNav').contains(document.activeElement); const old=screens.findIndex(s=>s[0]===current);direction=screens.findIndex(s=>s[0]===id)>=old?1:-1;current=id;render(true); if(restore&&!fromTour)$('#hubNav [data-hub="'+id+'"]').focus({preventScroll:true}); }
  function step(n,fromTour=false){navigate(screens[(screens.findIndex(s=>s[0]===current)+n+screens.length)%screens.length][0],fromTour);}
  function comments(index) {
    const key=A.state.mode+'-'+index, t=titles()[index], entries=Array.isArray(social.comments[key])?social.comments[key]:[];
    A.openModal(`<div class="modal-standard"><p class="caps accent">LOCAL DEMO CONVERSATION</p><h2 id="modalHeading">Let's talk ${esc(t.title)}.</h2><p class="intro-copy">Comments stay on this device. Nothing is posted publicly.</p><div id="communityComments">${entries.map(v=>`<div class="local-comment"><strong>@${esc(A.state.profile.handle)}</strong><p>${esc(v)}</p></div>`).join('')||'<p class="local-note">Be the first to leave a thought.</p>'}</div><form id="communityCommentForm"><label class="sr-only" for="communityComment">Your comment</label><textarea id="communityComment" placeholder="Your take..." required maxlength="500"></textarea><button class="btn primary">Add comment</button></form></div>`,'community');
    $('#communityCommentForm').onsubmit=e=>{e.preventDefault();const text=$('#communityComment').value.trim();if(!text)return;social.comments[key]=[...entries,text].slice(-50);A.persist();comments(index);$('#communityComment').focus();};
  }
  document.addEventListener('click',e=>{
    const b=e.target.closest('button,a');if(!b)return;
    if(b.hasAttribute('data-download')) {
      const url=window.MAMBO_CONFIG.apkUrl.trim();
      if(!url) return A.openModal('<div class="modal-standard"><p class="caps accent">MAMBO FOR ANDROID</p><h2 id="modalHeading">Your next obsession.<br>Soon in your pocket.</h2><p class="intro-copy">The APK download has not been added to this website yet. Explore the working preview while the Android download is being prepared.</p><button class="btn primary" id="apkExplore">Explore Mambo ↗</button></div>','download'), $('#apkExplore').onclick=()=>{A.closeModal();$('#app').scrollIntoView({behavior:A.reduced?'instant':'smooth'});};
      try { const target=new URL(url,location.href);if(!['https:','http:','file:'].includes(target.protocol))throw Error();const link=document.createElement('a');link.href=target.href;link.download='mambo.v1.0.5.7.apk';link.rel='noopener';document.body.appendChild(link);link.click();link.remove(); } catch {A.toast('The APK download link is not valid yet.');}
    } else if(b.dataset.hub) navigate(b.dataset.hub);
    else if(b.dataset.hubTag){tag=b.dataset.hubTag;render();}
    else if(b.dataset.shelf) document.getElementById(b.dataset.shelf)?.scrollBy({left:Number(b.dataset.step)*450,behavior:A.reduced?'instant':'smooth'});
    else if(b.dataset.like){const key=b.dataset.like;social.likes[key]=!social.likes[key];A.persist();const feedEl=$('#hubFeed');if(feedEl)feedEl.innerHTML=feed();else render();}
    else if(b.dataset.follow!==undefined){const i=b.dataset.follow;social.follows[i]=!social.follows[i];A.persist();b.textContent=social.follows[i]?'Following':'Follow +';b.setAttribute('aria-pressed',!!social.follows[i]);}
    else if(b.dataset.comments!==undefined)comments(Number(b.dataset.comments));
    else if(b.dataset.person!==undefined){const i=Number(b.dataset.person),p=people[i];A.openModal(`<div class="modal-standard"><p class="caps accent">SAMPLE COMMUNITY PROFILE</p><div class="social-avatar avatar-${i}">${p.letter}</div><h2 id="modalHeading">${p.name}</h2><p class="intro-copy">@${p.handle}<br>${p.bio}</p><button class="btn outline" data-follow="${i}" aria-pressed="${!!social.follows[i]}">${social.follows[i]?'Following':'Follow +'}</button><h3 style="margin-top:26px">Their kind of cinema</h3><div class="hub-grid profile-pick-grid">${titles().slice(i,i+4).map(card).join('')}</div></div>`,'person');}
    else if(b.dataset.list!==undefined){const l=lists[Number(b.dataset.list)];A.openModal(`<div class="modal-standard"><p class="caps accent">THE MAMBO EDIT</p><h2 id="modalHeading">${l.name}</h2><p class="intro-copy">${l.copy}</p><button class="btn primary" id="saveWholeList">Save collection +</button><div class="hub-grid profile-pick-grid">${l.ids.map(id=>card(A.byId(id))).join('')}</div></div>`,'collection');$('#saveWholeList').onclick=()=>{if(!A.state.folders.includes(l.name)&&A.state.folders.length<30)A.state.folders.push(l.name);const folder=A.state.folders.includes(l.name)?l.name:'Watchlist';l.ids.forEach(id=>A.saveTitle(id,folder,true));$('#saveWholeList').textContent='Saved to your library ✓';A.toast(l.ids.length+' titles saved to '+folder);};}
  });
  $('#hubPrevious').onclick=()=>step(-1);$('#hubNext').onclick=()=>step(1);
  $('#hubTour').onclick=()=>{if(tourTimer)return stopTour();if(A.reduced||P.lite)return A.toast('Use the arrows to explore at your own pace. Automatic tours are off in reduced-motion and Lite modes.');$('#hubTour').textContent='Pause tour Ⅱ';$('#hubTour').setAttribute('aria-pressed','true');tourTimer=setInterval(()=>{if(document.hidden||!hubVisible||$('#modalBackdrop').classList.contains('open'))return stopTour();step(1,true);},5500);};
  $('#performanceMode').onchange=e=>P.set(e.target.value);
  window.addEventListener('mambo:performance',()=>{stopTour();render();});
  window.addEventListener('mambo:motion',stopTour);
  window.addEventListener('mambo:mode',()=>{tag='All';search='';render(true);});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTour();});
  new IntersectionObserver(([e])=>{hubVisible=e.isIntersecting;if(!hubVisible)stopTour();}).observe($('#app'));
  let touch;
  $('#hubViewport').addEventListener('touchstart',e=>{touch=e.touches.length===1&&!e.target.closest('button,input,textarea,select,a,.hub-poster-row')?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null;},{passive:true});
  $('#hubViewport').addEventListener('touchend',e=>{if(!touch)return;const t=e.changedTouches[0],dx=t.clientX-touch.x,dy=t.clientY-touch.y;touch=null;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.7)step(dx<0?1:-1);},{passive:true});
  $('#hubViewport').addEventListener('touchcancel',()=>touch=null,{passive:true});
  if(window.MAMBO_CONFIG.apkUrl.trim())$('#apkStatus').textContent='Android APK v1.0.5.7 · Direct download';
  render();
})();
